version: "3.9"

services:
  db:
    container_name: sqlserverdb
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1433:1433
    volumes:
      - ./temp/mssqldata:/var/opt/mssql

volumes:
  mssqldata:
